services:
  db:
    container_name: classroom-api-db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=simonf
      - POSTGRES_PASSWORD=t
    volumes:
      - ./classroom-db-setup.sql:/docker-entrypoint-initdb.d/classroom-db-setup.sql


  api:
      container_name: classroom-api
      image: "postgrest/postgrest"
      ports:
      - "3000:3000"
      environment:
      - PGRST_DB_URI=postgresql://simonf:t@db:5432/postgres
      - PGRST_DB_SCHEMA=public
      - PGRST_DB_ANON_ROLE=simonf
      
      - PGRST_OPENAPI_SERVER_PROXY_URI=http://localhost:3000/
      depends_on:
        db:
          condition: service_started
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/